### ISSUE TITLE
Login/Signup Page Issues

### ISSUE THREAD

**Issue by ujjawal-1999** [ujjawal-1999/Alumni-Tracking-System#16]
- [x]  We can keep the icons above.

- [x] There needs to be some padding above that 'Welcome' test.

- [x]  We will have to keep space to render the flash message too.

- [x] Make the onClick animation a bit smooth.

- [x]  The onfocus outline is too dark and the width is also a more.

- [x]  Keep an option for the user to see the entered password

**Comment by Rajdeep-Paul-117** [comment]
added show password functionality, icons are shifted above, space for flash message and padding above 'welcome' added

**Comment by AnushaHazarika** [comment]
changed the onfocus outline and the onclick animation
